--
-- Core schema for the police dog register.
--
-- Notes on the design:
--   * Every table carries the same audit columns (version / created_at / updated_at / deleted_at).
--   * Nothing is ever physically removed. A row is "deleted" by stamping deleted_at,
--     which keeps the full audit history intact.
--   * The status and leaving-reason values are held in reference tables rather than as
--     database enums, because the task describes them as the values that are *currently*
--     possible - i.e. the force is expected to add to them over time.
--

-- ---------------------------------------------------------------------------
-- Suppliers: the breeder or kennels a dog came from. One supplier, many dogs.
-- ---------------------------------------------------------------------------
CREATE TABLE supplier
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(150) NOT NULL,
    contact_name  VARCHAR(150),
    contact_email VARCHAR(255),
    contact_phone VARCHAR(30),
    address       VARCHAR(500),
    version       BIGINT       NOT NULL DEFAULT 0,
    created_at    TIMESTAMP    NOT NULL,
    updated_at    TIMESTAMP    NOT NULL,
    deleted_at    TIMESTAMP
);

CREATE INDEX ix_supplier_name ON supplier (name);
CREATE INDEX ix_supplier_deleted_at ON supplier (deleted_at);

-- ---------------------------------------------------------------------------
-- Reference data: the statuses a dog can currently hold.
-- ---------------------------------------------------------------------------
CREATE TABLE dog_status
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code          VARCHAR(50)  NOT NULL,
    label         VARCHAR(100) NOT NULL,
    description   VARCHAR(500),
    display_order INTEGER      NOT NULL DEFAULT 0,
    version       BIGINT       NOT NULL DEFAULT 0,
    created_at    TIMESTAMP    NOT NULL,
    updated_at    TIMESTAMP    NOT NULL,
    deleted_at    TIMESTAMP
);

CREATE INDEX ix_dog_status_code ON dog_status (code);
CREATE INDEX ix_dog_status_deleted_at ON dog_status (deleted_at);

-- ---------------------------------------------------------------------------
-- Reference data: why a dog left the force.
-- ---------------------------------------------------------------------------
CREATE TABLE leaving_reason
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code          VARCHAR(50)  NOT NULL,
    label         VARCHAR(100) NOT NULL,
    description   VARCHAR(500),
    display_order INTEGER      NOT NULL DEFAULT 0,
    version       BIGINT       NOT NULL DEFAULT 0,
    created_at    TIMESTAMP    NOT NULL,
    updated_at    TIMESTAMP    NOT NULL,
    deleted_at    TIMESTAMP
);

CREATE INDEX ix_leaving_reason_code ON leaving_reason (code);
CREATE INDEX ix_leaving_reason_deleted_at ON leaving_reason (deleted_at);

-- ---------------------------------------------------------------------------
-- The dogs themselves.
-- ---------------------------------------------------------------------------
CREATE TABLE dog
(
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                      VARCHAR(100) NOT NULL,
    breed                     VARCHAR(100) NOT NULL,
    supplier_id               BIGINT       NOT NULL,
    badge_id                  VARCHAR(30),
    gender                    VARCHAR(10)  NOT NULL,
    birth_date                DATE         NOT NULL,
    date_acquired             DATE         NOT NULL,
    status_id                 BIGINT       NOT NULL,
    leaving_date              DATE,
    leaving_reason_id         BIGINT,
    kennelling_characteristic VARCHAR(2000),
    version                   BIGINT       NOT NULL DEFAULT 0,
    created_at                TIMESTAMP    NOT NULL,
    updated_at                TIMESTAMP    NOT NULL,
    deleted_at                TIMESTAMP,
    CONSTRAINT fk_dog_supplier FOREIGN KEY (supplier_id) REFERENCES supplier (id),
    CONSTRAINT fk_dog_status FOREIGN KEY (status_id) REFERENCES dog_status (id),
    CONSTRAINT fk_dog_leaving_reason FOREIGN KEY (leaving_reason_id) REFERENCES leaving_reason (id)
);

CREATE INDEX ix_dog_name ON dog (name);
CREATE INDEX ix_dog_breed ON dog (breed);
CREATE INDEX ix_dog_badge_id ON dog (badge_id);
CREATE INDEX ix_dog_supplier_id ON dog (supplier_id);
CREATE INDEX ix_dog_status_id ON dog (status_id);
CREATE INDEX ix_dog_deleted_at ON dog (deleted_at);
